# 공통 설정 파일
base_image: "public.ecr.aws/lambda/python:3.13"
python_version: "3.13"
chrome_version: "stable"  # 자동 감지
chrome_bin: "/opt/chrome/chrome"
chromedriver_path: "/opt/chromedriver/chromedriver"
lambda_handler: "app.handler"

# 시스템 라이브러리
system_packages:
  - "unzip"
  - "ca-certificates"
  - "nss"
  - "atk"
  - "at-spi2-core"
  - "gtk3"
  - "pango"
  - "libXcomposite"
  - "libXrandr"
  - "libXcursor"
  - "libXdamage"
  - "libXfixes"
  - "libXrender"
  - "libXi"
  - "libXScrnSaver"
  - "alsa-lib"
  - "cups-libs"
  - "libdrm"
  - "mesa-libgbm"
  - "dejavu-fonts-all"
  - "liberation-fonts"
  - "fontconfig"
